GET http://localhost:8080/devops_starter_war_exploded/api/xxx

###
POST http://localhost:8080/rest_day1_war_exploded/api/person
Content-Type: application/json

{"name": "First Property", "age": 20}

###
PUT http://localhost:8080/rest_day1_war_exploded/api/person/4
Content-Type: application/json

{"name": "First update", "age": 20}